import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Herder from '@/components/Header/Header';
import TanStackProvider from '@/components/Header/TanStackProvider/TanStackProvider';

const geistSans = Roboto({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <TanStackProvider>
          <Herder />
          {children}
        </TanStackProvider>
      </body>
    </html>
  );
}
